version: "3"

services:
  ankisyncd:
    build:
      context: .
    container_name: ankisyncd
    restart: always
    ports:
      - "127.0.0.1:27701:27701"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}